#!/bin/bash
source ${0%/*}/cgi.inc

id -Gn | grep -qw 'root\|i2c' || die "Must be root!"

runfor=$base/runfor/runfor
[ -x $runfor ] || die "require executable $runfor"

i2cio=$base/i2cio/i2cio
[ -x $i2cio ] || die "require executable $i2cio"

# Just invoke the i2cio command to filter stdin to stdout, but timeout if it hangs
$runfor 10 $i2cio
