#!/bin/bash -eu

# nuke children on exit
trap 'x=$?; kill $(jobs -p) &>/dev/null && wait $(jobs -p) || true; exit $x' EXIT

die() { echo $@ >&2; exit 1; }

(($#==2)) || die "Usage: $0 pionic_directory station_id"

pionic=$1
station=$2

echo "Default fixture driver"

# Show default screen, refresh on two taps in one second
while true; do
    printf "TEST STATION $station READY" | $pionic/cgi/display text fg=white bg=blue align=center point=40
    while true; do
        read || die "evdump unexpected EOF"
        read -t1 && break
    done
done < <($pionic/evdump/evdump -t1 -c272 -v1 mouse0 2>/dev/null)

