#!/bin/bash -eu

# start cgiserver and beacon if installed, and then reset the display when touched

# nuke children on exit
trap 'x=$?; kill $(jobs -p) &>/dev/null && wait $(jobs -p) || true; exit $x' EXIT

die() { echo $@ >&2; exit 1; }

(($#==2)) || die "Usage: $0 pionic_directory station_id"

pionic=$1
station=$2

echo "Starting default fixture driver"

# start daemons
pgrep -f cgiserver &>/dev/null || $pionic/cgi/cgiserver -p 80 -d $pionic/cgi &
if [ -d $pionic/beacon ]; then
    pgrep -f beacon &>/dev/null || $pionic/beacon/beacon send br0 &
fi

# Show default screen, refresh on two taps in one second
while true; do
    printf "TEST STATION $station READY" | $pionic/cgi/display text fg=white bg=blue align=center point=40
    while true; do
        read || die "evdump unexpected EOF"
        read -t1 && break
    done
done < <($pionic/evdump/evdump -t1 -c272 -v1 mouse0 2>/dev/null)

